### ISSUE TITLE
一杯目ネタ ~フロントエンドを語ろう~

### ISSUE THREAD

**Issue by ts-yokouchi-hiroki** [TeamSpiritInc/makanai-tech#1]
まかないてっく一杯目のネタ用issueです。

話してみたいこと、気になってること、聞いてみたいことetc...  
などをこちらのissueへコメントお願いいたします！

**Comment by s-yamazaki** [comment]
積読から。

* [Redux isn't slow, you're just doing it wrong - An optimization guide | React Rocket](http://reactrocket.com/post/react-redux-optimization/)

パフォーマンスチューニングの話かと思いきやメインは react-redux の connect() の仕様というかオプションについてっぽい。
ちょうど社内で話題になったこともあり。

* [ES8 was Released and here are its Main New Features 🔥](https://hackernoon.com/es8-was-released-and-here-are-its-main-new-features-ee9c394adf66)

ES8 リリースされましたね（もう１ヶ月たってる）
ここで書いてる仕様のほとんどは昨年末すでによしこさんがまとめてたぽい。
[今年のうちに知っておきたい！ES2017に入る5つの新仕様 - エンジニアをリングする](http://yoshiko.hatenablog.jp/entry/es2017)

**Comment by ts-yokouchi-hiroki** [comment]
CSS Frameworkつかってます？弊社ではLightning Design Systemをベースにしています。

Bootstrap、Foundation etc...いろいろあるフレームワーク、皆さんは実務で利用していますか？
もしくはフルスクラッチしてますか？その場合はどこまでフレームワーク化してますか？

**Comment by naoto86** [comment]
フロントエンド開発と、その学習で苦戦したこと。
例えば環境設定がうまくいかなかった！や、知ってて当たり前かのようにチュートリアル出てくる単語が分からず詰んだ！とか。

**Comment by s-yamazaki** [comment]
[Flexbox Froggy - A game for learning CSS flexbox](http://flexboxfroggy.com/)

Flexbox が学べてよかった

**Comment by masuP9** [comment]
アクセシビリティ対応（あえて対応と書きます）についてぶっちゃけたところをお聞きしたいお気持ち

- ナニソレおいしいの？ とか
- 正直難しい... とか
- 興味ない... とか
- 何からやっていいか分からん... とか
- やってるけど、これでいいのかどうか分からん... とか

**Comment by s-yamazaki** [comment]
フロントエンドのテストを皆さんどうされているのか教えていただきたいです。

**Comment by ts-yokouchi-hiroki** [comment]
アクセシビリティやCSS設計を考える上で、そもそもその前のデザインや設計が考えられていないと
消耗戦になりがちだと思います。
数年前からでてきたAtomic Designでは技術的な部分より、そういった組織としての取り組み方に比重が置かれており非常に興味深い内容でした。

皆さんはどうしていますでしょうか。

**Comment by brn** [comment]
フロントエンドの社内教育が聞きたいです。

**Comment by s-yamazaki** [comment]
ありがとうございました！
